/**
 * robots-sitemap.mjs — Astro integration that keeps robots.txt's Sitemap:
 * declaration in sync with the real sitemap filename generated by
 * @astrojs/sitemap (or any other sitemap generator that writes to the dist
 * root).
 *
 * Why this exists
 * ---------------
 * `public/robots.txt` is copied verbatim into `dist/`. Before this
 * integration, the `Sitemap:` line was hand-authored, which meant it could
 * (and did, in #163) drift from the actual sitemap filename Astro generated.
 * A hand-authored `Sitemap: https://nathanpayne.com/sitemap.xml` declaration
 * pointed at a URL that returned 404 because @astrojs/sitemap writes
 * `sitemap-index.xml`, not `sitemap.xml`. Google Search Console reads the
 * declared URL, got a 404, and indexing stalled.
 *
 * How it works
 * ------------
 * Runs at `astro:build:done`. Scans the dist root for a generated sitemap,
 * strips any existing `Sitemap:` lines from `dist/robots.txt`, and appends
 * a fresh `Sitemap:` line pointing at the real file. Throws if no sitemap
 * is found — that's a hard build failure rather than a silent broken
 * deploy, because "no sitemap" almost always indicates a broken build,
 * and a broken build should not ship.
 *
 * Resolution order for the sitemap file (first match wins):
 *   1. sitemap-index.xml   (default @astrojs/sitemap output)
 *   2. sitemap.xml         (legacy / some other generators)
 *   3. any `sitemap*.xml` at the dist root
 *
 * Source of truth: the file on disk in `dist/`.
 * Not the config. Not a constant. Not a hand-written robots.txt line.
 *
 * @see Issue #163 — LinkedIn crawler / indexing investigation
 * @see Issue #164 — Prevent robots.txt sitemap drift from Astro output
 */

import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SITEMAP_LINE_RE = /^\s*Sitemap:.*$/gim;

/**
 * Find the canonical sitemap file at the dist root.
 * Returns the basename (e.g. "sitemap-index.xml") or throws.
 */
async function findSitemapFile(distDir) {
  // 1. Prefer sitemap-index.xml
  try {
    await stat(join(distDir, 'sitemap-index.xml'));
    return 'sitemap-index.xml';
  } catch {
    // fall through
  }

  // 2. Fall back to sitemap.xml
  try {
    await stat(join(distDir, 'sitemap.xml'));
    return 'sitemap.xml';
  } catch {
    // fall through
  }

  // 3. Last resort: any sitemap*.xml at the root.
  // Sort entries so selection is deterministic when more than one
  // matches — readdir order is filesystem-dependent otherwise.
  const entries = (await readdir(distDir)).sort();
  const match = entries.find((f) => /^sitemap.*\.xml$/i.test(f));
  if (match) return match;

  throw new Error(
    'robots-sitemap: no sitemap file found in dist/. ' +
      'Expected sitemap-index.xml, sitemap.xml, or similar. ' +
      'Is @astrojs/sitemap configured and running?'
  );
}

/**
 * Strip any existing `Sitemap:` lines and append a fresh one.
 */
function rewriteRobotsTxt(existing, sitemapUrl) {
  // Remove all Sitemap: lines (there should be one or zero, but be defensive)
  let body = existing.replace(SITEMAP_LINE_RE, '').replace(/\n{3,}/g, '\n\n').trimEnd();

  // Ensure a single blank line separates the rules from the Sitemap directive
  if (body.length > 0) body += '\n\n';
  body += `Sitemap: ${sitemapUrl}\n`;
  return body;
}

export default function robotsSitemap() {
  // Captured from astro:config:done and reused in astro:build:done so we
  // don't hard-code the site URL.
  let resolvedSite;

  return {
    name: 'robots-sitemap',
    hooks: {
      'astro:config:done': ({ config }) => {
        // `config.site` is the absolute URL declared in astro.config.mjs.
        // @astrojs/sitemap already requires this to be set, so we can rely
        // on it — but fail loudly if it is somehow missing.
        if (!config.site) {
          throw new Error(
            'robots-sitemap: astro.config.mjs must declare a `site` URL. ' +
              '@astrojs/sitemap depends on this, and so do we.'
          );
        }
        resolvedSite = String(config.site).replace(/\/$/, '');
      },

      'astro:build:done': async ({ dir, logger }) => {
        // `dir` is a URL object. `dir.pathname` yields `/C:/path/...` on
        // Windows, which breaks `path.join`. Convert via `fileURLToPath`
        // per Astro's documented cross-platform pattern.
        const distDir = fileURLToPath(dir);
        const robotsPath = join(distDir, 'robots.txt');

        // robots.txt must exist — it ships from public/ and is a hard
        // requirement for the SEO plumbing this integration protects.
        let existing;
        try {
          existing = await readFile(robotsPath, 'utf-8');
        } catch (err) {
          throw new Error(
            `robots-sitemap: dist/robots.txt not found. ` +
              `Expected a public/robots.txt source file to copy through. ` +
              `(${err.code || err.message})`,
            { cause: err }
          );
        }

        const sitemapFile = await findSitemapFile(distDir);
        const sitemapUrl = `${resolvedSite}/${sitemapFile}`;

        const next = rewriteRobotsTxt(existing, sitemapUrl);
        if (next === existing) {
          logger.info(`robots.txt already points at ${sitemapUrl}`);
          return;
        }

        await writeFile(robotsPath, next, 'utf-8');
        logger.info(`robots.txt Sitemap line rewritten → ${sitemapUrl}`);
      },
    },
  };
}
